apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: server
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: theppakorn/backend:v0.1
        imagePullPolicy: Always
        name: team21-backend
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
